os: linux
dist: xenial

sudo: false
language: python
cache: pip
before_script:
  - pip install tox

# test script
script:  tox
after_success:
  - codecov

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=bandit
